### ISSUE TITLE
Production build of design preview does not have correct number of rows

### ISSUE THREAD

**Issue by sonofab1rd** [cdierkens/bluebird-cabinetry-and-design#165]
Something in the production build is causing the design preview to not have the correct css. So, the image grid is not displaying correctly.

**Comment by cdierkens** [comment]
Tailwind purges unused CSS, but can't purge dynamic classes like `md:col-span-${colSpan}`

See: https://tailwindcss.com/docs/controlling-file-size/#writing-purgeable-html
