### ISSUE TITLE
Fix error in Icons

### ISSUE THREAD

**Issue by sonofab1rd** [cdierkens/bluebird-cabinetry-and-design#180]
Something in the svg Icons is causing an error. InvalidCharacterError: Failed to execute 'createElement' on 'Document'

From what I googled, it seems to be something with the Icon svgs. 

This: https://github.com/doczjs/docz/issues/1184 says:
you should use a gatsby plugin

npm add gatsby-plugin-react-svg
create file gatsby-config.js

add

module.exports = {
    plugins: ['gatsby-plugin-react-svg']
}

But we have that...so very confusing

**Comment by sonofab1rd** [comment]
@cdierkens Can you run the app locally? I'm getting an error.

**Comment by cdierkens** [comment]
I'm running with no issue.

**Comment by sonofab1rd** [comment]
It's some kind of config issue.  I altered the gatsby-config from 
`{
      resolve: "gatsby-plugin-react-svg",
      options: {
        rule: {
          include: /icons\/.*\.svg/,
        },
      },
    },
`
to 
`"gatsby-plugin-react-svg",`
and it now runs

**Comment by sonofab1rd** [comment]
committed this to #117
