### ISSUE TITLE
Display the image number for example "1 of 15" images in the portfolio images light box.

### ISSUE THREAD

**Issue by cdierkens** [cdierkens/bluebird-cabinetry-and-design#294]

**Comment by sonofab1rd** [comment]
Played around with this a bit. Figured out that this is possible just by removing the Footer: null from components={{ Footer: null, Header, View }} in the Carousel in PortfolioImages . Not sure that's exactly what we are after, design wise. Also noticed it's possible to override the default styles. So maybe we put it in the footer, or maybe in the header. Will have to play with it some more.

**Comment by cdierkens** [comment]
Footer could make sense. My initial thoughts were focused on maximizing the
size of images. We could concede that since full screen is available users
can see it in a larger view already.

I like the idea of overriding styles instead of providing our own Header
and Footer component. I went with the custom component approach more for
speed than correctness, so there wasn’t a strong reason for using that
pattern beside the header’s Custom tagline text.

I’d just make sure you double check how it appears on mobile with a long
tagline and the numbers as you try approaches.

**Comment by sonofab1rd** [comment]
Okay, peep the 294-image-number branch. I got the footer text to display, and invert. It's pretty quick and dirty. But, was cool to figure out. It's possible to return a custom styles function. Maybe, that makes sense?

**Comment by sonofab1rd** [comment]
Moved the styles to customSyles object. Not sure how to pass props other than caption to footer caption. Maybe will play around with the Footer Component and have it return both FooterCaption and FooterCount
