### ISSUE TITLE
Update handwriting on about page to a more readable font.

### ISSUE THREAD

**Issue by cdierkens** [cdierkens/bluebird-cabinetry-and-design#325]

**Comment by sonofab1rd** [comment]
Showed Dana Pacifico, Cookie and Marck Script. She liked Cookie(my fave too!). Created branch 325-update-handwriting-font. Committed updates and pushed branch.

**Comment by cdierkens** [comment]
> Showed Dana Pacifico, Cookie and Marck Script. She liked Cookie(my fave too!). Created branch 325-update-handwriting-font. Committed updates and pushed branch.

@sonofab1rd Nice!

I just added Deploy Preview notifications that are supposed leave a comment on a PR you could use to see and share it live.
