### ISSUE TITLE
Reorganize the Portfolio photo metadata

### ISSUE THREAD

**Issue by sonofab1rd** [cdierkens/bluebird-cabinetry-and-design#726]
Possibly break "Tags" into separate categories.
- Tags
- Room
- Project
- Contractor(s)
- Interior Designer(s)

Also found Furniture Refinishing, Decorator

**Comment by cdierkens** [comment]
Could be useful to use "Albums" as a generic grouping in place of "Projects"

**Comment by cdierkens** [comment]
Could use some multi selects for the UI: https://react-select.com/home
