### ISSUE TITLE
Add WebImage schema object type

### ISSUE THREAD

**Issue by cdierkens** [cdierkens/bluebird-cabinetry-and-design#77]
Schema should have a required field "Description" string type that prompts the user to enter text into the alt attribute of the img tag. 
The subtext should instruct the user to describe the image.

Schema should also have an image type.

See https://webaim.org/techniques/alttext/

**Comment by sonofab1rd** [comment]
@cdierkens Can you have a look at my most recent commit on branch 2. I added the webImage to the schema. Let me know if this is what you had in mind. Thanks!
