### ISSUE TITLE
Add Design Style section to Home page

### ISSUE THREAD

**Issue by cdierkens** [cdierkens/bluebird-cabinetry-and-design#99]

**Comment by sonofab1rd** [comment]
@cdierkens Where are the images?

**Comment by cdierkens** [comment]
We can either pull them from google drive and hard code them or add a homeDesignGrid document to the schema.  We can pull some them from the google drive.

**Comment by sonofab1rd** [comment]
@cdierkens I did wind up needing a designPreviewImage object. It has fields: webImage, colspan and rowspan. I couldn't build the schema with designPreview's array of type object. I got a ...you can't use a generic object in an array... error.

**Comment by cdierkens** [comment]
@sonofab1rd Looks good! I went ahead and deploy the studio `graphql` endpoint for the  `development` dataset. You should be able to pull those images, on the web side now. Though I think there is a little bit more to do on the studio to make the **Design Preview** display like a singleton like *Home Carousel* does.

**Comment by sonofab1rd** [comment]
@cdierkens I made some adjustments to the designPreview and the designPreviewImage. The studio looks and behaves more appropriately. I still have an error... typeerror: cannot read property of undefined I thought it might go away when I uploaded some images and created the designPreview. But, not so.

**Comment by cdierkens** [comment]
@sonofab1rd I'll take a look and see if I see anything obvious.
